name: CI
on: [push]
env:
  CI: true
  ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node: [12, 14, 16]

    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: ${{ matrix.node }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Node.js dependencies
        run: |
          if ! [ -d "./node_modules" ]; then
            yarn install --frozen-lockfile
          fi

      - name: Run lint
        run: yarn lint

      - name: Test types
        run: npx tsc -p . --noEmit

      - name: Run tests
        run: yarn test

      - name: Build
        run: yarn build && yarn build:docs

      - name: Setup for deploy
        run: |
          set -ex

          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          npm whoami

      # prerelease versions must have a '-' to be released
      - name: Publish unstable
        if: "startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-') && matrix.node == 12"
        run: |
          npm publish --tag next

      # latest tags must not have a prerelease number
      - name: Publish
        if: "startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-') && matrix.node == 12"
        run: |
          npm publish
